# Generated by Django 5.1 on 2024-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_alter_product_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default=6667, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
