# Generated by Django 5.1 on 2024-09-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_delete_newsletter_remove_cart_user_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('most_popular', 'Most Popular')], default='most_popular', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clinic_app.category'),
        ),
    ]
