# Generated by Django 5.1 on 2024-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_remove_category_description_remove_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
