# Generated by Django 5.1 on 2024-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0012_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_based_authentication',
            field=models.BooleanField(default=True),
        ),
    ]
