# Generated by Django 5.1 on 2024-09-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0017_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
