# Generated by Django 5.1 on 2024-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0019_remove_product_section_product_view_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view_count',
            new_name='add_to_cart_count',
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('most_popular', 'Most Popular')], default='new_arrival', max_length=20),
            preserve_default=False,
        ),
    ]
