# Generated by Django 5.1 on 2024-10-03 10:03

from django.db import migrations

from django.db.models import F

def convert_delivery_location(apps, schema_editor):
    Profile = apps.get_model('clinic_app', 'Profile')
    Location = apps.get_model('clinic_app', 'Location')

    # Find all profiles with non-null delivery_location
    profiles_to_update = Profile.objects.exclude(delivery_location__isnull=True)

    for profile in profiles_to_update:
        if isinstance(profile.delivery_location, str):
            # Create a new Location object
            location = Location.objects.create(
                formatted_address=profile.delivery_location,
                street=profile.delivery_location  # You might want to adjust this
            )
            # Update the profile to use the new Location object
            profile.delivery_location = location
            profile.save()

def reverse_convert_delivery_location(apps, schema_editor):
    # If needed, write reverse migration logic here
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0022_location_formatted_address_alter_location_city_and_more'),  # replace with the name of your last migration
    ]

    operations = [
        migrations.RunPython(convert_delivery_location, reverse_convert_delivery_location),
    ]