# Generated by Django 5.1 on 2024-10-04 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0024_senderaddress_order_category_order_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state_code',
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='email',
            field=models.EmailField(default='david@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
