# Generated by Django 5.1 on 2024-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0025_remove_location_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
