# Generated by Django 5.1 on 2024-10-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0026_order_request_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_method',
            new_name='service_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='courier_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
