# Generated by Django 5.1 on 2024-10-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0029_order_courier_email_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
