# Generated by Django 5.1 on 2024-10-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0031_remove_location_city_remove_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='senderaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='senderaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='senderaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='senderaddress',
            name='street',
        ),
        migrations.RemoveField(
            model_name='senderaddress',
            name='street_no',
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
