# Generated by Django 5.1 on 2024-10-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0032_remove_senderaddress_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='request_token',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='senderaddress',
            name='email',
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='validation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='senderaddress',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sender_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('service_code', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_id', models.CharField(max_length=255, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('courier_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='clinic_app.order')),
            ],
        ),
    ]
