# Generated by Django 5.1 on 2024-10-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0033_remove_order_courier_email_remove_order_courier_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_dimension', to='clinic_app.product')),
            ],
        ),
    ]
