# Generated by Django 5.1 on 2024-10-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0034_packagedimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('picked_up', 'picked_up'), ('in_transit', 'in_transit'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
