# Generated by Django 5.1 on 2024-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0035_remove_cart_session_key_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='request_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
